version: '3'
services:
  jasperserver:
    image: jasperserver-pro:latest
    container_name: jasperserver
    # expose port 8080 and bind it to 8080 on host
    ports:
      - "8080:8080"
    # depends on js_db service
    depends_on:
      - js_db
    # point to env file with key=value entries
    env_file: env
    # following values will override settings from env_file
    environment:
      - DB_HOST=js_db
      
  js_db:
    image: postgres:10.1
    container_name: pgtest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: env